<!doctype html>
<!--[if IE]>
<?php require_once ERROR_UNSUPPORTED ?>
<![endif]-->
<html lang="en">
<head>
    <!--Define url-->
    <script>window.app = {baseUrl: <?= json_encode($this->urlArr['baseUrl']); ?>};</script>
    <!--Page Title-->
    <!--Favicons-->
    <?php
    if ($this->urlArr['pagename'] == "simpl") {
        echo '<title>Simpl</title>
        <link rel="apple-touch-icon" sizes="180x180" href="' . PageController::url('img/favicon-simpl/apple-touch-icon.png') . '">
        <link rel="icon" type="image/png" sizes="32x32" href="' . PageController::url('img/favicon-simpl/favicon-32x32.png') . '">
        <link rel="icon" type="image/png" sizes="16x16" href="' . PageController::url('img/favicon-simpl/favicon-16x16.png') . '">
        <link rel="manifest" href="' . PageController::url('img/favicon-simpl/site.webmanifest') . '">
        <link rel="mask-icon" href="' . PageController::url('img/favicon-simpl/safari-pinned-tab.svg') . '" color="#e52d2d">';
    } else {
        echo '<title>' . PAGENAME . '</title>
        <link rel="apple-touch-icon" sizes="180x180" href="' . PageController::url('img/favicon/apple-touch-icon.png') . '">
        <link rel="icon" type="image/png" sizes="32x32" href="' . PageController::url('img/favicon/favicon-32x32.png') . '">
        <link rel="icon" type="image/png" sizes="16x16" href="' . PageController::url('img/favicon/favicon-16x16.png') . '">
        <link rel="manifest" href="' . PageController::url('img/favicon/site.webmanifest') . '">
        <link rel="mask-icon" href="' . PageController::url('img/favicon/safari-pinned-tab.svg') . '" color="#587d9a">';
    }
    ?>
    <!--Meta and CSS-->
    <?php
    require_once META;
    require_once CSS;
    ?>
</head>
<body>
<?php
if ($this->urlArr['pagename'] == "home" || $this->urlArr['pagename'] == "") {
    echo '<div class="load-home" id="load">
            <div class="load-text text-wave center">Loading...</div>
          </div>';
} elseif ($this->urlArr['pagename'] == "projects") {
    echo '<div class="load-projects" id="load">
            <div class="load-text center">
              <div title="Loading..." class="glitch"> Loading...</div>
            </div>
          </div>';
} elseif ($this->urlArr['pagename'] == "simpl") {
    echo '<div class="load-simpl" id="load">
            <div class="load-text center">Loading...</div>
            <div class="band load-band"></div>
          </div>';
}
?>
<!--Navbar-->
<?php $this->get_part('navbar'); ?>
<!--Content-->
<section class="content" id="content">