<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Unsupported</title>

    <style>
        html, body {
            margin: 0;
            padding: 0;
            z-index: 10;
            overflow: hidden;
        }

        .unsupported {
            color: white;
            font-size: 24px;
            background-color: black;
            padding: 18px;
            height: 100vh;
            width: 100vw;
            display: table-cell;
            vertical-align: middle;
            text-align: center;
        }

        .unsupported-head {
            font-family: monospace;
            color: red;
            font-size: 32px;
            font-weight: 800;
            text-transform: uppercase;
        }

        .unsupported-text {
            color: #757575
        }
    </style>
</head>
<body>
<div class="unsupported">
    <span class="unsupported-head">
        <b>Internet Explorer is not supported on this site!</b>
    </span>
    <br>
    <span>This site uses modern technology that is <b>not</b> supported by IE! Please switch to a modern browser such as: </span>
    <a class="unsupported-text" href="https://www.google.com/intl/nl_nl/chrome/" target="_blank">Google Chrome</a>,
    <a class="unsupported-text" href="https://www.microsoft.com/nl-nl/edge" target="_blank">Microsoft Edge</a> or
    <a class="unsupported-text" href="https://www.mozilla.org/nl/firefox/new/" target="_blank">Firefox</a>!
</div>
</body>