<!--Set Charset-->
<meta charset="utf-8">

<!--IE Support-->
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9">

<!--Set Viewport-->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--Description-->
<meta name="description" content="Simpl is an HTML, PHP, CSS, SCSS and JavaScript framework!">

<!--Theme color-->
<meta name="msapplication-TileColor" content="#2b5797">
<meta name="theme-color" content="#ffffff">