<div class="page projects">
    <div class="page-header projects-header">
        <div class="page-row">
            <div class="page-col">
                <div class="projects-term">
<pre class="terminal" id="typewriter">
site:   Starting...

site:   Accessing database...

        username:   ********
        password:   **********

site:   Retrieving data...
site:   Compiling...
site:   Loading projects...

Time:   4432ms

File           Size              Version
<a class="term-link" href="#simpl">/simpl</a>         4.7 MB            2.1
<a class="term-link" href="#dashboard">/dashboard</a>     1.2 MB            1.2
<a class="term-link" href="#capitalz">/capitalz</a>      2.4 MB            1.1
<a class="term-link" href="#etws">/etws</a>          2.1 MB            1.4

Done. </pre>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body projects-body">
        <div class="page-row">
            <div class="page-col">

            </div>
        </div>
    </div>
</div>