<div class="page simpl">
    <div class="page-header simpl-header" id="simpl-header">
        <div class="page-row side-row">
            <div class="page-col side-col">
                <div class="page-row info-row">
                    <div class="page-col info-col center">
                        <div class="info-text">Simpl is a small, but smart and easy to use framework using the view-part system.</div>
                        <div class="info-text">It also comes with build-in Sass support using npm, the latest Jquery library and a collection of free fontawesome icons.</div>
                        <div class="info-text">
                            <a class="info-link" href="#simpl-body">Read more</a>
                        </div>
                    </div>
                </div>
                <div class="page-row apps-row">
                    <div class="page-col apps-col center">
                        <div class="icon-row">
                            <a href="https://www.php.net/" target="_blank" class="info-icon"><i class="fab fa-php"></i></a>
                            <a href="https://en.wikipedia.org/wiki/HTML5" target="_blank" class="info-icon"><i class="fab fa-html5"></i></a>
                            <a href="https://en.wikipedia.org/wiki/CSS" target="_blank" class="info-icon"><i class="fab fa-css3-alt"></i></a>
                        </div>
                        <div class="icon-row">
                            <a href="https://sass-lang.com/" target="_blank" class="info-icon"><i class="fab fa-sass"></i></a>
                            <a href="https://en.wikipedia.org/wiki/JavaScript" target="_blank" class="info-icon"><i class="fab fa-js"></i></a>
                            <a href="https://www.npmjs.com/" target="_blank" class="info-icon"><i class="fab fa-npm"></i></a>
                        </div>
                    </div>
                </div>
                <div class="page-row download-row">
                    <div class="page-col download-col center">
                        <a href="<?= PageController::url(SIMPL) ?>" target="_blank" class="simpl-download"><i class="fas fa-download"></i> Download</a>
                        <div class="download-detail">Version 2.1</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-row simpl-row">
            <div class="page-col simpl-col">
                <div class="page-row">
                    <div class="page-col center">
                        <div class="head-row">
                            <div class="simpl-head">Simpl</div>
                            <div class="simpl-detail">An easy-to-use PHP, HTML, CSS, SCSS and JavaScript framework!</div>
                            <a href="#simpl-body" class="simpl-extra">Download below</a>
                        </div>
                    </div>
                </div>
                <div class="page-row footer-row">
                    <div class="page-col center">
                        <div class="footer-simpl">
                            <a href="https://www.github.com/ijuantm/simpl/" target="_blank" class="footer-text"><i class="fab fa-github"></i> Fork me on GitHub!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body simpl-body" id="simpl-body">
        <div class="page-row">
            <div class="page-col center">
                TEST
            </div>
        </div>
        <div class="page-row">
            <div class="page-col center">
                TEST
            </div>
        </div>
    </div>
</div>